name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan action saat commit ke branch "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.17.0'  # Sesuaikan dengan versi Node.js Anda

    # Install dependensi
    - name: Install dependencies
      run: npm install

    # Build proyek
    - name: Build project
      run: npm run build

    # Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Direktori output hasil build
